[versions]
minecraft = "1.19"
quilt_mappings = "1.19+build.1" # Latest version is available at https://lambdaurora.dev/tools/import_quilt.html
quilt_loader = "0.17.1-beta.4" # Latest version is available at https://fabricmc.net/versions.html

quilted_fabric_api = "2.0.0-beta.1+0.56.3-1.19"
libzoomer = "0.5.0+1.19"
mod_menu = "4.0.0"
spruceui = "4.0.0+1.19"
mixin_extras = "0.0.11"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
quilt_mappings = { module = "org.quiltmc:quilt-mappings", version.ref = "quilt_mappings" }
quilt_loader = { module = "org.quiltmc:quilt-loader", version.ref = "quilt_loader" }

quilted_fabric_api = { module = "org.quiltmc.quilted-fabric-api:quilted-fabric-api", version.ref = "quilted_fabric_api" }
libzoomer = { module = "io.github.ennuil:LibZoomer", version.ref = "libzoomer" }
mod_menu = { module = "com.terraformersmc:modmenu", version.ref = "mod_menu" }
spruceui = { module = "dev.lambdaurora:spruceui", version.ref = "spruceui" }
mixin_extras = { module = "com.github.LlamaLad7:MixinExtras", version.ref = "mixin_extras" }

[plugins]
quilt_loom = { id = "org.quiltmc.loom", version = "0.12.+" }
machete = { id = "io.github.p03w.machete", version = "1.1.+" }
